spring:
  main:
    show_banner: true
  hadoop:
    fsUri: hdfs://localhost:8020
---

spring:
  profiles: lattice
  hadoop:
    socks:
      target: localhost
      port: 9000
    fsUri: hdfs://${spring.hadoop.socks.target}:${spring.hadoop.socks.port}
    config:
      hadoop.socks.server: ltchost:1099
      hadoop.rpc.socket.factory.class.default: org.apache.hadoop.net.SocksSocketFactory
---
